export enum SEARCH_ACTION_TYPES {
  SET_SEARCH_ITEMS = 'search/SET_SEARCH_ITEMS',
  SET_SEARCH_COUNT = 'search/SET_SEARCH_COUNT',
  FETCH_SEARCHED_PRODUCTS_START = 'search/FETCH_SEARCHED_PRODUCT_START',
  FETCH_SEARCHED_PRODUCTS_SUCCESS = 'search/FETCH_SEARCHED_PRODUCT_SUCCESS',
  FETCH_SEARCHED_PRODUCTS_FAILED = 'search/FETCH_SEARCHED_PRODUCT_FAILED'
}
