export enum PRODUCT_ACTION_TYPES {
  FETCH_PRODUCT_BY_ID_START = 'product/FETCH_PRODUCT_BY_ID_START',
  FETCH_PRODUCT_BY_ID_SUCCESS = 'product/FETCH_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_ID_FAILED = 'product/FETCH_PRODUCT_BY_ID_FAILED'
}
